# Generated by Django 3.1.7 on 2021-02-24 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210224_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='journal',
            name='categories',
            field=models.ManyToManyField(to='core.Category'),
        ),
    ]
